support multiple shas
app-sre/qontract-server pull request #88
Opened 2020-10-15 09:50 UTC by jmelis

2020-10-20 06:23 UTC, maorfr approved these changes
from just reading the description i understand that you thought of every scenario i could think of.
this is amazing work.

LGTM

2020-10-20 08:44 UTC, maorfr commented
qontract-reconcile PR: https://github.com/app-sre/qontract-reconcile/pull/1135

2020-10-20 10:31 UTC, rporres requested changes
This is an impressive job. A few comments and suggestions here and there...

One thing I don't particularly like is breaking changes... Especially since we're doing `GET`s with `query` params, e.g. https://github.com/openshift/aws-account-operator/pull/493/files, and it makes sense that we're able to do a select with a query string via `GET` (on top of the `POST` support, I'd do both)

2020-10-20 10:31 UTC, rporres commented on test/multishas/multishas.test.ts
> +});
missing test on bad bundle reload?

2020-10-20 18:05 UTC, jmelis commented
> One thing I don't particularly like is breaking changes... Especially since we're doing GETs with query params, e.g. https://github.com/openshift/aws-account-operator/pull/493/files, and it makes sense that we're able to do a select with a query string via GET (on top of the POST support, I'd do both)

Reimplemented and updated PR description.

2020-10-20 18:08 UTC, jmelis commented on src/metrics.ts
> +  name: 'qontract_server_router_stack',
done

2020-10-20 18:09 UTC, jmelis commented on src/metrics.ts
> +  name: 'qontract_server_cache_bundle',
done

2020-10-20 18:09 UTC, jmelis commented on src/metrics.ts
> +  name: 'qontract_server_cache_bundle_cache',
done

2020-10-20 18:09 UTC, jmelis commented on src/metrics.ts
> +    datafilesGuage.set({ schema: schemaName }, schemaCount[schemaName]),
done

2020-10-20 18:09 UTC, jmelis commented on src/metrics.ts
> +  // Set the Guage based on counted metrics
done

2020-10-20 18:10 UTC, jmelis commented on src/server.ts
> +// sha expiration time (in ms). Defaults to 1h.
done

2020-10-20 18:12 UTC, jmelis commented on src/server.ts
> +      res.status(503).send('error parsing bundle, not replacing');
No, it just means that no new data will be loaded. The server will continue working as if `/reload` had not been called.

2020-10-20 18:16 UTC, jmelis commented on test/multishas/multishas.test.ts
> +});
Good idea. Implemented.

2020-10-20 18:23 UTC, jmelis commented on src/server.ts
> +  const expiration = Date.now() + BUNDLE_SHA_TTL;
I'm not sure I understand! can you elaborate?

2020-10-20 18:30 UTC, jmelis commented on src/server.ts
> +      // versions of express without warning.
Good idea. Just created this issue: https://github.com/expressjs/express/issues/4436

2020-10-20 18:38 UTC, rporres commented on src/server.ts
> +  const expiration = Date.now() + BUNDLE_SHA_TTL;
If this was a cache outside the process, you would want to keep the timestamp where it was created instead of the expiration, because if you change the value of the TTL you would have a lot of objects with an outdated expiration date. But in this case the discussion is academic, because the only way to change the TTL is restarting the server which will throw away all the objects 😄

2020-10-20 18:40 UTC, rporres commented on src/metrics.ts
> +  name: 'qontract_server_bundle_object_shas_cache',
why not `qontract_server_bundle_cache_object_shas`?

2020-10-20 19:54 UTC, rporres commented
And don't hate me too much, please convert the relevant bits of the description of this PR into proper documentation.

2020-10-21 07:35 UTC, jmelis commented on src/server.ts
> +  const expiration = Date.now() + BUNDLE_SHA_TTL;
agreed!

2020-10-21 07:36 UTC, jmelis commented on src/metrics.ts
> +  name: 'qontract_server_bundle_object_shas_cache',
fixed

2020-10-21 08:52 UTC, jmelis commented
@rporres I have updated the README.md, it has been neglected so thanks for pointing it out.

2020-10-21 09:12 UTC, rporres approved these changes
Great stuff

2020-10-21 11:06 UTC, merged